#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

exec "C:/Users/uzayr/AppData/Roaming/xPacks/@xpack-dev-tools/windows-build-tools/4.4.1-2.1/.content/bin/busybox.exe"   "$@"
