name: Unit Test

on:
  pull_request:
    type: [opened, synchronize]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Initialize Docker
        run: bash ./tools/run_docker.bash init

      - name: Build and run tests
        run: bash ./tools/run_docker.bash test
